apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/coreos/kube-prometheus?ref=master
- custom-metrics-apiservice.yaml
- metrics-server.yaml
- grafana-ingress.yaml
- grafana-pvc.yaml
- jitsi-dashboard-configmap.yaml
- prometheus-roleBindingSpecificNamespaces.yaml
- prometheus-roleSpecificNamespaces.yaml
- jvb-pod-monitor.yaml
- prosody-pod-monitor.yaml
- bbb-service.yaml
- bbb-service-monitor.yaml
- haproxy-pod-monitor.yaml

patchesStrategicMerge:
- metrics-server-patch.yaml
- grafana-deployment-patch.yaml
- prometheus-adapter-config-map-patch.yaml
