apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jitsi
  labels:
    k8s-app: web
  name: web
spec:
  template:
    spec:
      # avoid that pods of different shards share zone
      # nodeSelector:
      #   topology.kubernetes.io/zone: ZONE_1
      containers:
        - name: web
          env:
            - name: XMPP_SERVER
              value: shard-0-prosody
            - name: XMPP_BOSH_URL_BASE
              value: http://shard-0-prosody:5280
