bases:
  - ../jitsi-base

patchesStrategicMerge:
  - jvb-hpa-patch.yaml
  - jvb-statefulset-patch.yaml
  - jicofo-deployment-patch.yaml
  - web-deployment-patch.yaml
  - prosody-deployment-patch.yaml

namespace: jitsi

namePrefix: shard-1-

commonLabels:
  shard: "1"
