apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jitsi
  labels:
    k8s-app: prosody
  name: prosody
spec:
  selector:
    matchLabels:
      shard: "1"
  template:
    spec:
      # avoid that pods of different shards share zone
      # nodeSelector:
      #   topology.kubernetes.io/zone: ZONE_2
    metadata:
      labels:
        shard: "1"
