apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: fluentd
          env:
            - name:  FLUENT_ELASTICSEARCH_HOST
              value: "elasticsearch-es-http.logging.svc.cluster.local"
            - name:  FLUENT_ELASTICSEARCH_PORT
              value: "9200"
            - name: FLUENT_ELASTICSEARCH_SCHEME
              value: "https"
            - name: FLUENT_ELASTICSEARCH_SSL_VERIFY
              value: "false" # not necessary within cluster
            # delete fluentd user
            - $patch: delete
              name: FLUENT_ELASTICSEARCH_USER
            # delete fluentd password
            - $patch: delete
              name: FLUENT_ELASTICSEARCH_PASSWORD
            # this secret is of form username:password and will be split by the startup script
            - name: FLUENT_ELASTICSEARCH_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-user-fluentd
                  key: users
          command: ["bash", "-c"]
          args:
            - >-
              export FLUENT_ELASTICSEARCH_USER=${FLUENT_ELASTICSEARCH_USER_PASSWORD%%:*};
              export FLUENT_ELASTICSEARCH_PASSWORD=${FLUENT_ELASTICSEARCH_USER_PASSWORD##*:};
              exec tini -- /fluentd/entrypoint.sh
