apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: monitoring
spec:
  template:
    spec:
      containers:
        - name: grafana
          env:
            - name: GF_SERVER_DOMAIN
              value: "jitsi.messenger.schule"
